# This file was generated by chatGPT

# 1. Base image
FROM python:3.9.22-bookworm

# 2. Set working directory
WORKDIR /py-jwt-auth

# 3. Copy requirements and install
COPY requirement.txt .
RUN pip install --no-cache-dir -r requirement.txt

# 4. Copy your project-- project files from local machine to image
COPY . .

# 5. Run the FastAPI app
CMD ["uvicorn", "api.app:api", "--host", "0.0.0.0", "--port", "8080"]
